config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations',
                     omniauth_callbacks: "users/omniauth_callbacks" }
                     
  authenticated :user do
    root 'users#dashboard', as: :authenticated_root
  end

  post 'users/find_friends', to: 'users#find_friends'

  root 'public#public'

  resources :users do
    member do
      get :follows, :followers
    end
  end

  resources :posts do
    member do
      get :liked_by
    end
    resources :comments  
  end

  get '/post/myblogs', to: 'posts#myblogs'

  resources :friend_requests, only: [:create, :index, :destroy, :update]
  resources :friends, only: [:index, :destroy]  

  resources :relationships, only: [:create, :destroy]

  resources :comments, only: :show do
    member do
      get :liked_by
    end
  end

  resources :likes, only: [:create, :destroy]
  resources :comment_likes, only: [:create, :destroy]

  resources :tags, only: [:index, :show]
  get 'tagged', to: 'posts#tagged'

  resources :subscribers, only: [:create] do
    member do
      get :unsubscribe
    end
  end

  
  post '/rate' => 'rater#create', :as => 'rate'

  get 'home', to: 'users#dashboard'

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/post.rb
class Post < ActiveRecord::Base
	after_create :send_email_to_subscribers

	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :nested_comments, through: :comments, source: :children
	has_many :likes
	has_many :liked_by, through: :likes, source: :user
	
	validates :user_id, presence: true
	validates :title,  presence: true
	validates :content, presence: true

	has_attached_file :image,
	 styles: { small: "64x64", med: "100x100", large: "300x300" }
	validates_attachment :image,
	 	content_type: { content_type: ["image/jpg", "image/jpeg", "image/png",
	 															 "image/gif"] }
	 									
	ratyrate_rateable "content"

	acts_as_taggable_on :tags

	self.per_page = 15

	def self.search(search)
  	self.where("title LIKE :search OR content LIKE :search", 
                {search: "%#{search}%"})
	end

	def to_param
    [id, title.parameterize].join("-")
  end

  def is_liked_by
  	self.liked_by
  end

  def remove_post
  	self.destroy
  end

  def has_comments
  	self.comments.includes(:user, :liked_by, :children).where(reply_to: nil)
  end

  def is_liked_by?(user)
  	self.liked_by.include?(user)
  end

	private

	def send_email_to_subscribers
	  Subscriber.all.each do |subscriber|
	  	SubscriptionMailer.delay.send_email(subscriber.email, self)
	  end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  #to display all posts with pagination
  def index
    if params[:search]
      @posts = Post.search(params[:search])
              .paginate(page: params[:page])
              .includes(:user).order("updated_at DESC")
    else
      @posts = Post.paginate(page: params[:page])
              .includes(:user).order("updated_at DESC")
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  #to show the content of each post including its comments and ratings
  def show
    @users = @post.is_liked_by
    @comments = @post.has_comments
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  #to edit a post
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  #to create a new post
  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = 'Post was successfully created.'
      redirect_to @post 
    else
      flash[:notice] = 'Post could not be created. Try again.'
      render :new
    end
  end

  #to update a post
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.js
      else
        format.html { render :edit }
        format.js
      end
    end
  end

  #to destroy a post
  def destroy
    @post.remove_post
    respond_to do |format|
      format.html { redirect_to posts_path, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #to show all posts of current user
  def myblogs
    if params[:search]
      @posts = current_user.posts.search(params[:search]).
               paginate(page: params[:page]).order("updated_at DESC")
    else
      @posts = current_user.posts.paginate(page: params[:page]).
               order("updated_at DESC")
    end
  end

  #to show posts with a certain tag
  def tagged
    if params[:tag].present? 
      @posts = Post.tagged_with(params[:tag])
    else 
      @posts = Post.all
    end  
  end

  #to find the users who have liked the post
  def liked_by
    post = Post.find_by(:id => params[:id])
  end

  private
  
    def set_post
      @post = Post.includes(:user, :tags).find_by(:id => params[:id])
      if @post.blank?
        redirect_to :posts,
         :flash => { :notice => "You tried to access a non-existing post." }
      end
    end

    def post_params
      params.require(:post).permit(:title, :content, :image, :tag_list)
    end

    def check_user
      if @post.user_id != current_user.id
        redirect_to :posts,
         :flash => { :notice => "You cannot change other's posts." }
      end
    end
end

app/helpers/posts_helper.rb
include ActsAsTaggableOn::TagsHelper
module PostsHelper
end

app/views/posts/shared/_all_posts.html.erb
<table class="table table-hover" style="margin-top: -20px;">
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to "#{post.title}",post %></td>
        <td>
          <% if post.user_id != current_user.id %>
            <%= post.user.name %>
          <% else %>
            <%= 'me' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/shared/_edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div id="title"><h1>Editing Post</h1> </div>
		<%= render 'posts/shared/form' %>
		<%= link_to 'Show', @post %> |
		<%= link_to 'Back', posts_path %>
	</div>
</div>
			 	
			

app/views/posts/shared/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.cktext_area :content %>
  </div>

  <div class="field">
    <%= f.label :add_tags %>
    <span class="glyphicon glyphicon-tag"></span>
    <%= f.text_field :tag_list, class: "form-control" %>
  </div>

  <div>
     <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.submit "Post", class: "input-lg btn btn-primary" %>
  </div>
<% end %>

app/views/posts/shared/_liked_by_modal.html.erb
<div id="liked_by_Modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      </div>
      <div class="modal-body">
        <table class="table-hover">
          <% users.each do |user| %>
            <tr>
              <td>
                <div class="round-image-50">
                  <%= image_tag(user.avatar.url(:thumb)) %>
                </div>
              </td>
              <td><%= link_to "#{user.name}", user_path(user) %></td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

app/views/posts/shared/_my_posts.html.erb
<%= will_paginate %>
<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="10">Title</th>    
    </tr>
  </thead>
  <tbody>
    <% posts.each do |post| %>
      <tr>
        <td colspan="10"><%= link_to "#{post.title}",post %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate %>

app/views/posts/shared/_post_details.html.erb
<div class="animated flipInX"> <h1 id="post_title"><%= post.title %></h1></div>
<p>
  <div id="post_content">
    <%= post.content.html_safe %>
    <% if post.user_id == current_user.id %>
      <div class="drop-down-post">
        <div class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="glyphicon glyphicon-cog"></span>
          </a>
          
          <div class="dropdown-menu">
            <%= link_to "<i class=\"glyphicon glyphicon-pencil\"></i>".html_safe, edit_post_path(@post), remote: true %>
            <%= link_to "<i class=\"glyphicon glyphicon-trash\"></i>".html_safe, @post, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <% if post.image_file_name != nil %>
    <div id="post_image">
      <%= link_to image_tag(post.image.url(:large)), post.image.url %>
    </div>
  <% end %>
  <% if post.tags.any? %>
    <span class="glyphicon glyphicon-tags">
      <% post.tags.each do |tag| %>
        <%= link_to tag.name, tagged_path(:tag => tag.name) %>
      <% end %>
    </span>
  <% end %>
</p>

app/views/posts/shared/_post_likes_count.html.erb
<% if post.likes.count != 0 %>
  <%= link_to "#{post.likes.count} Likes", "#", "data-toggle" => "modal", "data-target" => "#liked_by_Modal" %>
<% end %>