config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations',
                     omniauth_callbacks: "users/omniauth_callbacks" }
                     
  authenticated :user do
    root 'users#dashboard', as: :authenticated_root
  end

  post 'users/find_friends', to: 'users#find_friends'

  root 'public#public'

  resources :users do
    member do
      get :follows, :followers
    end
  end

  resources :posts do
    member do
      get :liked_by
    end
    resources :comments  
  end

  get '/post/myblogs', to: 'posts#myblogs'

  resources :friend_requests, only: [:create, :index, :destroy, :update]
  resources :friends, only: [:index, :destroy]  

  resources :relationships, only: [:create, :destroy]

  resources :comments, only: :show do
    member do
      get :liked_by
    end
  end

  resources :likes, only: [:create, :destroy]
  resources :comment_likes, only: [:create, :destroy]

  resources :tags, only: [:index, :show]
  get 'tagged', to: 'posts#tagged'

  resources :subscribers, only: [:create] do
    member do
      get :unsubscribe
    end
  end

  
  post '/rate' => 'rater#create', :as => 'rate'

  get 'home', to: 'users#dashboard'

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy

  has_many :comments, dependent: :destroy

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :friend_requests, dependent: :destroy
  has_many :pending_requests, through: :friend_requests, source: :friend

  has_many :follow_relationships, class_name: "Relationship",
                              foreign_key: "follower_id", dependent: :destroy
  has_many :followed_relationships,  class_name: "Relationship",
                              foreign_key: "followed_id", dependent: :destroy
  has_many :follows, through: :follow_relationships, source: :followed
  has_many :followers, through: :followed_relationships, source: :follower

  has_many :likes, dependent: :destroy
  has_many :likes_post, through: :likes,
                        source: :post, dependent: :destroy
                        
  has_many :comment_likes, dependent: :destroy
  has_many :likes_comment, through: :comment_likes,
                           source: :comment, dependent: :destroy

  has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100" }

  ratyrate_rater

  geocoded_by :address
  after_validation :geocode
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :omniauthable, :omniauth_providers => [:facebook],
         :authentication_keys => [:login]

  VALID_FB_REGEX = /(?:https?:\/\/)?(?:www\.)?facebook\.com\/(?:(?:\w)*#!\/)?(?:pages\/)?(?:[\w\-]*\/)*([\w\-\.]*)/
  VALID_STRING_REGEX = /([\w\-\'])([\s]+)?([\w\-\'])/

  validates :name,  presence: true, 
    length: { maximum: 50 }, 
    format: { with: VALID_STRING_REGEX }, unless: :uid
  validates :city,  presence: true, format: { with: VALID_STRING_REGEX }, 
                    unless: :uid
  validates :username,  presence: true, uniqueness: true, unless: :uid
  validates :fb_profile, presence: true,
                    format: { with: VALID_FB_REGEX }, unless: :uid

  has_attached_file :avatar, :styles => { :medium => "300x300>",
                                          :thumb => "100x100#" },
                  :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  # for facebook login
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name 
      user.confirmed_at = Time.now
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  #to make a user follow another user
  def follow(other_user)
    follow_relationships.create(followed_id: other_user.id)
  end

  #to stop user from following other user
  def unfollow(other_user)
    follow_relationships.find_by(followed_id: other_user.id).destroy
  end

  #for the feed to be shown in the dashboard
  def feed
    follow_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Post.where("user_id IN (#{follow_ids})
                     OR user_id = :user_id", user_id: id)
  end

  def follow_relation(user)
    self.follow_relationships.find_by(followed_id: user)
  end

  def friendship(friend)
    self.friends.where(id: friend.id)
  end

  def friend_request(friend)
    self.friend_requests.find_by(friend_id: friend)
  end

  def has_friend?(friend)
    self.friends.where(id: friend.id).present?
  end

  def remove_friend(friend)
    self.friends.destroy(friend)
    friend.friends.destroy(self)
  end

  def has_sent_friend_request_to?(friend)
    self.friend_requests.find_by(friend_id: friend).present?
  end

  def is_following?(user)
    self.follows.include?(user)
  end

  def is_followed_by
    self.followers.count
  end

  def is_following
    self.follows.count
  end

  #Storing city as the address to be used by geocoder 
  def address
    "#{city}"
  end

  #to login using email or username
  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  #to use friendly urls
  def to_param
    [id, name.parameterize].join("-")
  end
  
  #implements searching users 
  def self.search(search) 
    where("name LIKE :search  OR city LIKE :search", {search: "%#{search}%"})
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      bypass_sign_in(@user)
      redirect_to home_path
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to new_user_registration_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :follows, :followers]
	$nearby_friends = nil

	#to show all users using pagination
	def index
    if params[:search]
      @users = User.search(params[:search])
              .paginate(page: params[:page])
              .order("updated_at DESC")
    else
      @users = User.paginate(page: params[:page])
              .order("updated_at DESC")
    end
    user_collection
	end

	#to edit the password of current user
	def edit
		@user = User.find_by(id: current_user)
	end

	#to update the password of current user
	def update
		@user = User.find_by(id: current_user)
		if @user.update_with_password(user_params)
      flash[:notice] = "Password successfully updated."
			redirect_to new_user_session_path
		else
			render 'edit'
		end	
	end

	#to show the profile of the users
	def show
    about_user
	end

	#to list the people current user follows
	def follows
    @users = @user.follows
  end

  #to list the followers of the current user
  def followers
    @users = @user.followers
  end

  #to display the feed 
	def dashboard
  	if !user_signed_in?
  		redirect_to new_user_session_path
  	else
  		@user = current_user
  		@posts = @user.feed
  	end
  end

  #to find friends nearby based on current location of the user
  def find_friends
	 	$nearby_friends = current_user.friends.near(params[:current_location], 50)
	 	redirect_to :home
  end

	private

	def user_params
    params.require(:user).permit(:current_password,
     :password, :password_confirmation, :avatar, :latitude, :longitude)
  end

  def set_user
  	@user = User.includes(:posts).find_by(id: params[:id])
    if @user == nil
      redirect_to :users,
         :flash => { :notice => "You tried to access a non-existing user." }
    end
  end

  def user_collection
    @users_collection = []
    @all_users = @users
    @all_users.each do |user|
      each_user = { name: user.name, city: user.city, fb_profile: user.fb_profile,
          user: user, avatar: user.avatar,
          is_friend: current_user.has_friend?(user),
          has_got_friend_request: current_user.has_sent_friend_request_to?(user),
          has_sent_friend_request: user.has_sent_friend_request_to?(current_user),
          friendship: current_user.friendship(user),
          friend_request_sent: current_user.friend_request(user),
          is_followed: current_user.is_following?(user),
          follow_relation: current_user.follow_relation(user)  }
      @users_collection << each_user
    end
  end

  def about_user
    @about_user = {name: @user.name, city: @user.city,
        about: @user.about, avatar: @user.avatar, 
        followers_count: @user.is_followed_by,
        following_count: @user.is_following,
        is_friend: current_user.has_friend?(@user),
        has_got_friend_request: current_user.has_sent_friend_request_to?(@user),
        has_sent_friend_request: @user.has_sent_friend_request_to?(current_user),
        friendship: current_user.friendship(@user),
        friend_request_sent: current_user.friend_request(@user),
        is_followed: current_user.is_following?(@user),
        follow_relation: current_user.follow_relation(@user),
        posts: @user.posts,
        user: @user }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_add_friend_link.html.erb
<span id="add_friend_<%= user.id %>">
  <%= link_to "<i class=\"glyphicon glyphicon-plus\"></i><i class=\"glyphicon glyphicon-user\"></i>".html_safe, friend_requests_path(friend_id: user),method: :post, remote: true %>
</span>

app/views/users/shared/_current_user_posts.html.erb
<table class="table table-hover">
	<thead>
		<th>Posts</th>
	</thead>
	<% posts.each do |post|%>
		<tbody>
			<tr>
				<td>
					<div class="box">
						<div>
							<h3><%= link_to "#{post.title}", post_path(post) %></h3>
						</div>

						<div><%= post.content.html_safe %></div>
							<% if post.image_file_name != nil %>
								<div><%= image_tag(post.image.url(:med)) %></div>
							<% end %>

						<div>
							<%= link_to "#{post.user.name}", user_path(post.user_id) %>
							<%= post.created_at %>
						</div>
						
						<p class="read-more"><%= link_to "Read More", post_path(post), class: "button" %></p>
					</div>
				</td>
			</tr>
		</tbody>
	<% end %>
</table>

app/views/users/shared/_flash_message.html.erb
<% if flash[:notice] %>
	<div class="notice"><%= notice %></div>
  <%= alert %>
<% end %>

app/views/users/shared/_flash_notice.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/users/shared/_follow_link.html.erb
<span  id="follow_span_<%= user.id%>">
	<%= link_to "Follow", relationships_path(:followed_id => user), method: :post, remote: true %>
</span>

app/views/users/shared/_followers_modal.html.erb
<div id="followers_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
      <h2 id="modal_heading"> Followers </h2>
      </div>
      <div class="modal-body">
        <table class="table-hover">
          <% user.followers.each do |user| %>
            <tr>
              <td>
                <div class="round-image-50">
                  <%= image_tag(user.avatar.url(:thumb)) %>
                </div>
              </td>
              <td><%= link_to "#{user.name}", user_path(user) %></td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_follows_modal.html.erb
<div id="follows_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h2 id="modal_heading"> Follow </h2>
      </div>
      <div class="modal-body">
        <table class="table-hover">
          <% user.follows.each do |user| %>
            <tr>
              <td>
                <div class="round-image-50">
                  <%= image_tag(user.avatar.url(:thumb)) %>
                </div>
              </td>
              <td><%= link_to "#{user.name}", user_path(user) %></td>
            </tr>
          <% end %>
        </table>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_friends.html.erb
<div class="friends">
	<%= form_tag controller: "users", action: "find_friends", method: "post" do%>
		<p>Enter current city to find friends nearby:</p>
	  <p id="current_location"><%= text_field_tag 'current_location' %></p>
	  <p><%= submit_tag "Find", class: "btn-primary"%></p>
	<% end %>

		<% if $nearby_friends != nil %>
			<% $nearby_friends.each do |friend| %>
				<table>
					<tbody>
						<tr>
							<td>
								<div class="round-image-50">
									<%= image_tag(friend.avatar.url(:thumb)) %>
								</div>
							</td>
							<td>
								<%= link_to "#{friend.name}", user_path(friend) %>
							</td>
						</tr>
					</tbody>
				</table>
			<% end %>
		<% end %>
</div>

app/views/users/shared/_remove_friend_request_link.html.erb
<span id="remove_friend_request_<%= friend.id %>">
  <%= link_to "Remove Request", friend_request_path(request), method: :delete, remote: true %>
</span>

app/views/users/shared/_show_all_users.html.erb
<%= will_paginate %>
<section class="products">
	<% users_collection.each do |user| %>
	  <div class="product-card">
	    <div class="product-image">
	      <%= image_tag(user[:avatar].url(:medium)) %>
	    </div>
	    <div class="product-info">
	      <h5><%= link_to "#{user[:name]}", user_path(user[:user]) %></h5>
	      <h6><%= user[:city] %></h6>
	      <% if !user[:fb_profile].blank? %>
	        <h6><%= link_to user[:fb_profile], user[:fb_profile] %></h6>
	      <% end %>
	      <% if user[:user] != current_user %> 
		      <% if user[:is_friend] %>
		      	<span class="glyphicon glyphicon-user"></span> |
		     	<% elsif user[:has_got_friend_request] %>
		     		<%= render partial: "users/shared/remove_friend_request_link", locals: {friend: user[:user], request: user[:friend_request_sent]} %> |
		     	<% elsif user[:has_sent_friend_request] %>
		     		<%= link_to "Respond to friend request", friend_requests_path %> |
		     	<% else %> 
            <%= render partial: "users/shared/add_friend_link", locals: {user: user[:user]} %> |
		     	<% end %>

		     	<% if !user[:is_followed] %>
		     		<%= render partial: "users/shared/follow_link", locals: {user: user[:user]}%>
		     	<% else %>
		     		<%= render partial: "users/shared/unfollow_link", locals: {user: user[:user], relationship: user[:follow_relation]}%>
		     	<% end %>
		    <% end %>
	    </div>
	  </div>
	<% end %>
</section>
<%= will_paginate %>

app/views/users/shared/_unfollow_link.html.erb
<span id="unfollow_span_<%= user.id%>">
	<%= link_to "Unfollow",relationship_path(relationship), method: :delete, remote: true %>
</span>

app/views/users/shared/_user_profile.html.erb
<div id="user_profile">
	<h1 id="title"><%= user[:name] %></h1>
	<% if user[:city].any? %>
		<h5 id="about_user">
			<span class="glyphicon glyphicon-map-marker"><span>
			<%= user[:city] %>
		</h5>
	<% end %>

	<% if !user[:about].blank? %>
		<h5 id="about-user">"<%= user[:about] %>"</h5>
	<% end %>
	
	<div id="profile_image">
		<div class="round-image-profile">
			<%= image_tag(user[:avatar].url(:thumb)) %>
		</div>
	</div>

	<p>
		<%= link_to "Followers", "#", "data-toggle" => "modal", "data-target" => "#followers_modal" %>
		<span class="badge"><%= user[:followers_count] %></span> |
		<%= link_to "Following", "#", "data-toggle" => "modal", "data-target" => "#follows_modal" %>
		<span class="badge"><%= user[:following_count] %></span>
		<%= render partial: "users/shared/followers_modal", locals:{ user: user[:user]} %>
		<%= render partial: "users/shared/follows_modal", locals:{ user: user[:user]} %>
	</p>

	<% if user[:user] != current_user %>
		<% if user[:is_friend] %>
      <span class="glyphicon glyphicon-user"></span> 
    <% elsif user[:has_sent_friend_request]%>
      <%= link_to "Respond to friend request", friend_requests_path %> 
    <% elsif user[:has_got_friend_request] %>
     	<%= render partial: "users/shared/remove_friend_request_link", locals: {friend: user[:user], request: user[:friend_request_sent]} %> 
    <% else %>
      <%= render partial: "users/shared/add_friend_link", locals: {user: user[:user]} %>
    <% end %> |

		<% if !user[:is_followed] %>
			<%= render partial: "users/shared/follow_link", locals: {user: user[:user]} %>
		<% else %>
			<%= render partial: "users/shared/unfollow_link", locals: {user: user[:user], relationship: user[:follow_relation]}%>
		<% end %>
	<% end %>
</div>