config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations',
                     omniauth_callbacks: "users/omniauth_callbacks" }
                     
  authenticated :user do
    root 'users#dashboard', as: :authenticated_root
  end

  post 'users/find_friends', to: 'users#find_friends'

  root 'public#public'

  resources :users do
    member do
      get :follows, :followers
    end
  end

  resources :posts do
    member do
      get :liked_by
    end
    resources :comments  
  end

  get '/post/myblogs', to: 'posts#myblogs'

  resources :friend_requests, only: [:create, :index, :destroy, :update]
  resources :friends, only: [:index, :destroy]  

  resources :relationships, only: [:create, :destroy]

  resources :comments, only: :show do
    member do
      get :liked_by
    end
  end

  resources :likes, only: [:create, :destroy]
  resources :comment_likes, only: [:create, :destroy]

  resources :tags, only: [:index, :show]
  get 'tagged', to: 'posts#tagged'

  resources :subscribers, only: [:create] do
    member do
      get :unsubscribe
    end
  end

  
  post '/rate' => 'rater#create', :as => 'rate'

  get 'home', to: 'users#dashboard'

  mount Ckeditor::Engine => '/ckeditor'

end

app/views/shared/_comment.html.erb
<div style=" margin-left: <%= l %>px; ">
  <% if l == 0 %>
    <% l = 50 %>
  <% end %>
  <% comments.order("created_at DESC").each do |comment| %>
    <%= render partial: "comments/shared/print_comment", locals: {comment: comment, l: 0} %>

    <div class="replies" id="<%= "replies_all_#{comment.id}" %>">
      <% comments = comment.children.includes(:post, :liked_by, :user) %>
      <%= render partial: "shared/comment", locals: {comments: comments, l: l * 0.9, post: post} %>
    </div>
    
    <div id="reply_print_<%= "#{comment.id}"%>" %></div>

    <div  id="reply_div<%= "#{comment.id}" %>", class="add-reply comment-form-div">
      <div id="comment_form_image">
        <div class="round-image-50">
          <%= image_tag(@post.user.avatar.url(:thumb)) %>
        </div>
      </div>
      <div id="comment_form_content">
        <%= form_for([post, post.comments.build], remote: true) do |f| %>
          <%= f.hidden_field :reply_to, value: comment.id %>
          <%= f.hidden_field :level, value: comment.level + 1 %>
            <% if !comment.base_reply %>
              <%= f.hidden_field :base_reply, value: comment.id %>
            <% else %>
              <%= f.hidden_field :base_reply, value: comment.base_reply %>
            <% end %>   
          <%= f.text_area :content, class: 'form-control new-reply' %><br>
          <%= f.submit class:"btn btn-primary" %>
        <% end %>
      </div>
    </div>
  <% end %>
</div> 

app/views/shared/_comment_like.html.erb
<span id="comment-like<%=@comment.id%>">
  <span class="glyphicon glyphicon-thumbs-up">
    <%= link_to "Like", comment_likes_path(:comment_id => @comment), method: :post, remote: true %>
  </span>
</span> 

app/views/shared/_comment_likes_count.html.erb
<% if comment.comment_likes.count != 0 %>
  <%= link_to "#{comment.comment_likes.count} Likes",liked_by_comment_path(comment) %> |
<% end %>

app/views/shared/_comment_unlike.html.erb
<span id="comment-unlike<%= @comment.id %>">
  <span class="glyphicon glyphicon-thumbs-down">
    <%= link_to "Unlike", comment_like_path(@like), method: :delete, remote: true %>
  </span>
</span>

app/views/shared/_current_user_posts.html.erb
<table class="table table-hover">
	<thead>
		<th>Posts</th>
	</thead>
	<% @user.posts.each do |post|%>
		<tbody>
			<tr>
				<td>
					<div>
						<h3><%= link_to "#{post.title}", post_path(post) %></h3>
					</div>
					<div><%= post.content.html_safe %></div>
						<% if post.image_file_name != nil %>
							<div><%= image_tag(post.image.url(:med)) %></div>
						<% end %>
					<div>
						<%= link_to "#{post.user.name}", user_path(post.user_id) %>
						<%= post.created_at %>
					</div>
				</td>
			</tr>
		</tbody>
	<% end %>
</table>

app/views/shared/_feed.html.erb
<table class="table">
	<thead>
		<th>Post</th>
	</thead>
	<tbody>
		<% @posts.includes(:user).order("updated_at DESC").each do |post| %>
			<tr>
				<td>
					<div class="box">
						<div>
							<h2 id="post-heading"><%= link_to "#{post.title}", post_path(post) %></h2>
						</div>

						<div>
							<%= link_to "#{post.user.name}", user_path(post.user_id) %>
							<%= post.created_at.strftime("%I:%M%p") %>
						</div>

						<div>
							<%= post.content.html_safe %>
						</div>

						<% if post.image_file_name != nil %>
							<div><%= image_tag(post.image.url(:large)) %></div>
						<% end %>
						
						<p class="read-more"><%= link_to "Read More", post_path(post), class: "button" %></p>
					</div>	
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/shared/_new_comment_form.html.erb
<div class="comment-form-div">
	<div id="comment_form_image">
		<div class="round-image-50">
      <%= image_tag(@post.user.avatar.url(:thumb)) %>
    </div>
	</div>
	<div id="comment_form_content">
	<%= form_for([@post, @post.comments.build], remote: true, class: "new-comment-form") do |f| %>
		<%= f.text_field :content, class: 'form-control field new-comment' %>
		<%= f.submit class:"btn btn-primary field" %>
	<% end %>
	<% if @post.user_id == current_user %>
		<%= link_to 'Edit', edit_post_path(@post) %> |
	<% end %>
	</div>
</div>

app/views/shared/_reply_div.html.erb
<div  id="reply_div<%= "#{comment.id}" %>", class="add-reply comment-form-div">
  <div id="comment_form_image">
    <div class="round-image-50">
      <%= image_tag(@post.user.avatar.url(:thumb)) %>
    </div>
  </div>
  <div id="comment_form_content">
    <%= form_for([post, post.comments.build], remote: true) do |f| %>
      <%= f.hidden_field :reply_to, value: comment.id %>
      <%= f.hidden_field :level, value: comment.level + 1 %>
      <% if !comment.base_reply %>
        <%= f.hidden_field :base_reply, value: comment.id %>
      <% else %>
        <%= f.hidden_field :base_reply, value: comment.base_reply %>
      <% end %>   
      <%= f.text_area :content, class: 'form-control new-reply' %><br>
      <%= f.submit class:"btn btn-primary" %>
    <% end %>
  </div>
</div>