config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations',
                     omniauth_callbacks: "users/omniauth_callbacks" }
                     
  authenticated :user do
    root 'users#dashboard', as: :authenticated_root
  end

  post 'users/find_friends', to: 'users#find_friends'

  root 'public#public'

  resources :users do
    member do
      get :follows, :followers
    end
  end

  resources :posts do
    member do
      get :liked_by
    end
    resources :comments  
  end

  get '/post/myblogs', to: 'posts#myblogs'

  resources :friend_requests, only: [:create, :index, :destroy, :update]
  resources :friends, only: [:index, :destroy]  

  resources :relationships, only: [:create, :destroy]

  resources :comments, only: :show do
    member do
      get :liked_by
    end
  end

  resources :likes, only: [:create, :destroy]
  resources :comment_likes, only: [:create, :destroy]

  resources :tags, only: [:index, :show]
  get 'tagged', to: 'posts#tagged'

  resources :subscribers, only: [:create] do
    member do
      get :unsubscribe
    end
  end

  
  post '/rate' => 'rater#create', :as => 'rate'

  get 'home', to: 'users#dashboard'

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
	has_many :children, class_name: "Comment", foreign_key: "reply_to",
																						 dependent: :destroy
	belongs_to :parent, class_name: "Comment", foreign_key: "reply_to"
	has_many :comment_likes
	has_many :liked_by, through: :comment_likes, source: :user

	validates :user_id, presence: true
	validates :post_id, presence: true
	validates :content, presence: true

	def has_been_liked_by
		self.liked_by
	end

	def is_liked_by?(user)
		self.liked_by.include?(user)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_post, only:[:new, :create, :show]
	before_action :check_user, only:[:edit, :update]
	before_action :check_user_for_destroy, only:[:destroy]
	#creates the comment
	def new
		@comment = Comment.new
		respond_to do |format|
			format.js
		end
	end

	def create
		@comment = Comment.new(comment_params.merge({post_id: @post.id,
																		 user_id: current_user.id}))
		if @comment.save
      respond_to do |format|
        format.html {redirect_to :back}
        format.js
      end
    end
	end

	def edit
		@comment = @post.comments.find_by(id: params[:id])
		respond_to do |format|
			format.js
		end
	end

	def update
		@comment = @post.comments.find_by(id: params[:id])
  	if @comment.update(comment_params)
  		respond_to do |format|
  			format.js
  		end
  	end
	end

	#destroys the comment
	def destroy
	  @comment = @post.comments.find_by(id: params[:id])
	  @comment_ids = [@comment.id]
		if(@comment.children)
			find_all_child_comment(@comment.children)
		end
    @comment.destroy
    respond_to do |format|
    	format.html {redirect_to post_path(@post)}
    	format.js
    end
	end
	
	#for displaying the comments of a post
	def show
	  @comment = @post.comments.find_by(id: params[:id])
	end

	#to display the list of users who liked the comment
	def liked_by
		comment = Comment.includes(:liked_by).find_by(id: params[:id])
		@users = comment.has_been_liked_by									
	end

	private
	
	def comment_params
		params.require(:comment).permit(:content, :reply_to,
																		 :base_reply, :level)
	end
	
	def set_post
		@post = Post.includes(:comments).find_by(id: params[:post_id])
	end

	def find_all_child_comment comments
		comments.each do |comment|
			@comment_ids.push(comment.id)
			if(comment.children)
				find_all_child_comment(comment.children)
			end
		end
	end

	def check_user
		@post = set_post
		@comment = @post.comments.find_by(id: params[:id])
    if @comment.user_id != current_user.id
      redirect_to :back,
      :flash => { :notice => "You cannot change other's comments." }
    end
  end

  def check_user_for_destroy
  	@post = set_post
		@comment = @post.comments.find_by(id: params[:id])
		if @comment.user_id != current_user.id || @post.user_id != current_user.id
      redirect_to :back,
      :flash => { :notice => "You cannot change other's comments." }
    end
  end

end

app/views/comments/shared/_edit_comment_form.html.erb
<%= form_for([post, comment], method: :put,
											remote: true, id: "comment_edit_form#{comment.id}") do |f| %>
	<%= f.text_area :content, autocomplete: "off", class: 'form-control', 
															id: "comment_edit_content#{comment.id}", value: comment.content %>
	<%= f.submit class:"btn btn-primary field" %>
<% end %>

app/views/comments/shared/_liked_by.html.erb
<table class="table table-hover">
	<tbody>
		<% @users.each do |user| %>
			<tr>
				<td><%= link_to "#{user.name}", user_path(user) %></td> 
			</tr>
		<% end %>
	</tbody>
</table>

app/views/comments/shared/_print_comment.html.erb
<div id="whole_comment_<%= comment.id %>" style=" margin-left: <%= l %>px; "> 
  <div class="round-image-50"; style="float: left;">
    <%= image_tag(comment.user.avatar.url(:thumb)) %>
  </div>
  <div id="reply_content"> 
    <div style="float: left;">
      <strong><%= comment.user.name %></strong>
        <span id="time_ago">
          --<%= time_ago_in_words(comment.created_at) %> ago 
        </span>
    </div>   
    <div>"<%= comment.content %>"</div>
    <div>
      <div>
        <span id="comment-likes-count<%= comment.id%>">
          <%= render partial: "shared/comment_likes_count", locals: {comment: comment} %>
        </span>
           
        <% if !comment.is_liked_by?(current_user) %>
          <span id="comment-like<%=comment.id%>">
            <span class="glyphicon glyphicon-thumbs-up">
              <%= link_to "Like", comment_likes_path(comment_id: comment), method: :post, remote: true %>
            </span>
          </span> 
        <% else %>
          <% like = current_user.comment_likes.find_by(comment_id: comment) %>
          <span id="comment-unlike<%=comment.id%>">
            <span class="glyphicon glyphicon-thumbs-down">
              <%= link_to "Unlike", comment_like_path(like), method: :delete, remote: true %>
            </span>
          </span>
        <% end %>
      </div>
      
      <%= link_to "Reply", "javascript:void(0);", 
                  id: "addcomment_#{comment.id}", class: "reply"%> 

      <div class="comment-options">             
        <% if comment.user_id == current_user.id %>
          <%= link_to "<i class=\"glyphicon glyphicon-pencil\"></i>".html_safe, edit_post_comment_path(@post, comment), remote: true %>
        <% end %>
        
        <% if comment.post.user == current_user || comment.user_id == current_user.id %>
          <%= link_to "<i class=\"glyphicon glyphicon-trash\"></i>".html_safe, [comment.post, comment], method: :delete,
                data: { confirm: 'Are you sure?' }, remote: true %>
        <% end %> 
      </div>
     

      <% if (comment.children.length > 0) %>
        <%= link_to "All Replies", "javascript:void(0);", class: "comment-reply", id: "comment_show_#{comment.id}" %>
        <%= link_to "Hide Replies", "javascript:void(0);",  class: "comment-hide", id: "comment_hide_#{comment.id}" %>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/shared/_reply_comment_form.html.erb
<%= form_for([post, post.comments.build], remote: true) do |f| %>
        <%= f.hidden_field :reply_to, value: comment.id %>
        <%= f.hidden_field :level, value: comment.level + 1 %>
          <% if !comment.base_reply %>
            <%= f.hidden_field :base_reply, value: comment.id %>
          <% else %>
            <%= f.hidden_field :base_reply, value: comment.base_reply %>
          <% end %>   
        <%= f.text_area :content, class: 'form-control new-reply' %><br>
        <%= f.submit class:"btn btn-primary" %>
      <% end %>